definitions:
  User:
    properties:
      country:
        type: string
        x-go-name: Country
      email:
        type: string
        x-go-name: Email
      firstname:
        type: string
        x-go-name: Firstname
      lastname:
        type: string
        x-go-name: Lastname
    type: object
    x-go-package: _/Users/ackers/Documents/Developer/go/Projects/CredentialsCapture/models/credentials
paths:
  /save:
    post:
      description: Save Credentials to the Database
      operationId: Save
      parameters:
      - description: Save Credentials
        in: body
        name: User
        required: true
        schema:
          $ref: '#/definitions/User'
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "500":
          description: Internal Error (Unable to Save to Database)
      tags:
      - Users
swagger: "2.0"
