name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2


    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16


    - name: Test
      run: go test  -v -coverprofile=profile.cov ./...

    - name: TestResults
      run: go tool cover -func profile.cov


